*
      SUBROUTINE BI_F77_MPI_TESTALL(COUNT, REQUESTS, FLAG, STATS, IERR)
      INCLUDE 'mpif.h'
      INTEGER COUNT, FLAG, IERR
      INTEGER REQUESTS(*), STATS(MPI_STATUS_SIZE, *)
      LOGICAL FLAG2
*
      CALL MPI_TESTALL(COUNT, REQUESTS, FLAG2, STATS, IERR)
      IF (FLAG2) THEN
         FLAG = 1
      ELSE
         FLAG = 0
      END IF
*
      RETURN
      END
