*
      SUBROUTINE BI_F77_MPI_TEST(REQUEST, FLAG, STATUS, IERR)
      INCLUDE 'mpif.h'
      INTEGER FLAG, REQUEST, IERR
      INTEGER STATUS(MPI_STATUS_SIZE)
      LOGICAL FLAG2
*
      CALL MPI_TEST(REQUEST, FLAG2, STATUS, IERR)
      IF (FLAG2) THEN
         FLAG = 1
      ELSE
         FLAG = 0
      END IF
*
      RETURN
      END
