*
      SUBROUTINE BI_F77_MPI_OP_CREATE(FUNC, COMMUTE, OP, IERR)
      INCLUDE 'mpif.h'
      EXTERNAL FUNC
      INTEGER COMMUTE, OP, IERR
      LOGICAL COMMUTE2
*
      IF (COMMUTE .EQ. 0) THEN
         COMMUTE2 = .FALSE.
      ELSE
         COMMUTE2 = .TRUE.
      END IF
      CALL MPI_OP_CREATE(FUNC, COMMUTE2, OP, IERR)
*
      RETURN
      END
